---
global:
  repoURL: test
  targetRevision: main

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

aapManifest:
  key: secret/data/hub/aap-manifest

aap:
  eda_disabled: false
  hub_disabled: true
  lightspeed_disabled: true

configJob:
  image: quay.io/validatedpatterns/vp-ocaas-config-container:latest
  schedule: "10 */2 * * *"
  activeDeadlineSeconds: 3600
  imagePullPolicy: Always
  configTimeout: 1800

serviceAccountName: aap-config-sa
serviceAccountNamespace: ansible-automation-platform

# Validation job configuration
validationJob:
  disabled: false
  activeDeadlineSeconds: 600

# RBAC configuration using vp-rbac subchart
vp-rbac:
  serviceAccounts:
    aap-config-sa:
      namespace: ansible-automation-platform
      roleBindings:
        roles:
          - create-secrets

  roles:
    create-secrets:
      rules:
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["create", "get", "list"]
