---
galaxy_info:
  author: your name
  description: Install and configure Red Hat Identity Management (IDM)
  company: your company
  license: BSD
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - idm
    - ipa
    - identity
    - redhat
    - firewalld

dependencies: []

