clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    - ansible-automation-platform
    - golang-external-secrets
    - open-cluster-management
    - vault
    - group-sync-operator
  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.14
    aap-operator:
      name: ansible-automation-platform-operator
      namespace: ansible-automation-platform
      channel: stable-2.5
    group-sync-operator:
      name: group-sync-operator
      namespace: group-sync-operator
      channel: alpha
      source: community-operators
  argoProjects:
    - hub
    - infrastructure
  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
    - '/overrides/values-{{ $.Values.global.clusterVersion }}-{{ $.Values.clusterGroup.name }}.yaml'
    - '/values-omnicloud-as-a-service.yaml'
  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      argoProject: hub
      chart: acm
      chartVersion: 0.1.*
    vault:
      name: vault
      namespace: vault
      argoProject: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      argoProject: hub
      chart: golang-external-secrets
      chartVersion: 0.1.*
    aap-config:
      disabled: true
      name: aap-config
      namespace: ansible-automation-platform
      argoProject: hub
      path: charts/hub/aap-config
    hive:
      disabled: true
      name: hive-clusters
      namespace: hive
      project: infrastructure
      path: charts/all/infrastructure/hiveClusters
    group-sync:
      disabled: true
      name: group-sync-config
      namespace: group-sync-operator
      project: infrastructure
      path: charts/all/infrastructure/group-sync
    ldap-oauth:
      disabled: true
      name: ldap-oauth
      namespace: openshift-config
      project: infrastructure
      path: charts/all/infrastructure/oauth
  imperative:
    jobs:
      - name: hello-world
        # ansible playbook to be run
        playbook: rhvp.cluster_utils.hello_world
        # per playbook timeout in seconds
        timeout: 234
        # verbosity: "-v"
  managedClusterGroups:
    exampleRegion:
      name: devops
      acmlabels:
        - name: clusterGroup
          value: devops
      helmOverrides:
        - name: clusterGroup.isHubCluster
          value: false
