clusterGroup:
  name: devops
  isHubCluster: false
  namespaces:
    - golang-external-secrets
    - devops
  # The only subscription on spokes is gitops which gets managed by ACM
  subscriptions:
    clair:
      channel: stable-3.15
      name: container-security-operator
      source: redhat-operators
    devspaces:
      channel: stable
      name: devspaces
      source: redhat-operators
    webterminal:
      channel: fast
      name: web-terminal
      source: redhat-operators
    tekton:
      channel: latest
      name: openshift-pipelines-operator-rh
      source: redhat-operators
  argoProjects:
    - eso
    - devops
  applications:
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      argoProject: eso
      chart: golang-external-secrets
      chartVersion: 0.1.*
    rbac:
      name: rbac
      namespace: devops
      argoProject: devops
      path: charts/all/infrastructure/rbac
    nexus:
      name: nexus
      namespace: devops
      argoProject: devops
      path: charts/all/devops-tools/nexus
    sonarqube:
      name: sonarqube
      namespace: devops
      argoProject: devops
      path: charts/all/devops-tools/sonarqube
    selenium:
      name: selenium-hub
      namespace: devops
      argoProject: devops
      path: charts/all/devops-tools/selenium-hub
    selenium-chrome:
      name: selenium-node-chrome
      namespace: devops
      argoProject: devops
      path: charts/all/devops-tools/selenium-node-chrome
    selenium-firefox:
      name: selenium-node-firefox
      namespace: devops
      argoProject: devops
      path: charts/all/devops-tools/selenium-node-firefox
  imperative:
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://validatedpatterns.io/patterns/multicloud-gitops/mcg-imperative-actions/
    jobs:
      - name: hello-world
        # ansible playbook to be run
        playbook: rhvp.cluster_utils.hello_world
        # per playbook timeout in seconds
        timeout: 234
        # verbosity: "-v"
  # Explicitly mention the cluster-state based overrides we plan to use for this pattern.
  # We can use self-referential variables because the chart calls the tpl function with these variables defined
  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
    # To mirror the "Classic" magic include structure, the clusterGroup would need all of these:
    # sharedValueFiles:
    #   - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
    #   - '/overrides/values-{{ $.Values.global.clusterPlatform }}-{{ $.Values.global.clusterVersion }}.yaml'
    #   - '/overrides/values-{{ $.Values.global.clusterPlatform }}-{{ $.Values.clusterGroup.name }}.yaml'
    #   - '/overrides/values-{{ $.Values.global.clusterVersion }}-{{ $.Values.clusterGroup.name }}.yaml"
