---
global:
  pattern: omnicloud-as-a-service
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
  git:
    repoUpstreamURL: https://github.com/validatedpatterns-sandbox/omnicloud-as-a-service
    revision: rhdp
