---
apiVersion: "tower.ansible.com/v1alpha1"
kind: AnsibleProject
metadata:
  name: ansible-project
  namespace: ansible-automation-platform
spec:
  branch: {{ .Values.global.targetRevision }}
  connection_secret: aap-login-token
  description: "Ansible project to wrap jobs interacting with the ciphetrust manager"
  name: ocaas-project
  organization: Default
  repo: {{ .Values.global.repoURL }}
  scm_type: git