---
galaxy_info:
  author: your name
  description: Provision EC2 instances with public IPs
  company: your company
  license: BSD
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - aws
    - ec2
    - cloud
    - provisioning

dependencies: []

