---
# defaults file for clusterdeploy
create: "{{ create_cluster | default('false') }}"
clusterdeploy_destroy: >-
  {{
    clusterdeploy_destroy_cluster | default(destroy_cluster | default('false'))
  }}
# Render templates for debugging
debug_task: false

user_provided_credentials: false

cluster:
  namespace: hive
  clusterset: default

cloudConfig:
  azure:
    cloudName: AzurePublicCloud
