# Generate the secrets for user provided credentials
- name: Create pull secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ cluster.name }}-pull-secret"
        namespace: "{{ cluster.name }}"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ lookup('file', '~/.pullsecret.json') | b64encode }}"

- name: Create AWS credentials secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'aws-credentials.yaml.j2') | from_yaml }}"
  when: cloud.provider == 'Amazon'

- name: Create GCP credentials secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ cluster.name }}-{{ cloud.provider | lower }}-credentials"
        namespace: "{{ cluster.name }}"
      type:
        Opaque
      data:
        osServiceAccount.json: "{{ lookup('file', '~/.gcp/osServiceAccount.json') | b64encode }}"
  when: cloud.provider == 'Google'

- name: Create Azure credentials secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ cluster.name }}-{{ cloud.provider | lower }}-credentials"
        namespace: "{{ cluster.name }}"
      type: Opaque
      data:
        osServicePrincipal.json: "{{ lookup('file', '~/.azure/osServicePrincipal.json') | b64encode }}"
  when: cloud.provider == 'Azure'

- name: Generate the clusterDeployment template
  ansible.builtin.template:
    src: clusterDeployment.yaml.j2
    dest: "{{ deployment_config_dir }}/clusterdeployment.yaml"
    mode: "0644"
