---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: eso-push-ocaas-mgr-token
  namespace: hive
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: {{ .Values.secretStore.name }}
  selector:
    secret:
      name: ocaas-mgr-token
  template:
    data:
      bearer_token: '{{ `{{ index . "token" | toString }}` }}'
  data:
    - match:
        secretKey: bearer_token
        remoteRef:
          remoteKey: {{ .Values.ocaasClusterCreds.key | default "secret/data/hub/ocaas-cluster-creds" }}
          property: bearer_token
  refreshInterval: 1h
  updatePolicy: Replace
  deletionPolicy: Delete
